import { FormEvent, useEffect, useState } from 'react';

import { Button, PageHeader } from '../../components/ui/PageHeader';
import { deleteTag, listTags, saveTag } from '../../lib/blogService';
import type { BlogTag } from '../../types/blog';
import { slugify } from '../../utils/blog';

export function TagsPage() {
  const [items, setItems] = useState<BlogTag[]>([]); const [editing, setEditing] = useState<BlogTag | null>(null); const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function load() { setItems(await listTags()); }
  useEffect(() => { void load().catch((err) => setError(err.message)); }, []);
  function reset() { setEditing(null); setName(''); setSlug(''); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); try { await saveTag({ id: editing?.id, name, slug: slug || slugify(name) }); setMessage(editing ? 'Tag updated.' : 'Tag created.'); reset(); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save tag.'); } }
  return <div className="space-y-8"><PageHeader eyebrow="Tags" title="Blog Tags" description="Manage reusable tags for article filtering and editorial organization." />{error ? <p className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p> : null}{message ? <p className="rounded-2xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</p> : null}<div className="grid gap-6 lg:grid-cols-[24rem_1fr]"><form onSubmit={submit} className="rounded-2xl border border-brand-border bg-white p-5 shadow-sm"><h2 className="font-extrabold">{editing ? 'Edit Tag' : 'New Tag'}</h2><label className="mt-4 block text-sm font-bold">Name</label><input value={name} onChange={(e) => { setName(e.target.value); if (!editing) setSlug(slugify(e.target.value)); }} required className="mt-2 h-11 w-full rounded-xl border border-brand-border px-3 text-sm" /><label className="mt-4 block text-sm font-bold">Slug</label><input value={slug} onChange={(e) => setSlug(slugify(e.target.value))} required className="mt-2 h-11 w-full rounded-xl border border-brand-border px-3 text-sm" /><div className="mt-5 flex gap-2"><Button type="submit">{editing ? 'Update' : 'Create'}</Button>{editing ? <button type="button" onClick={reset} className="rounded-xl border border-brand-border px-4 text-sm font-bold">Cancel</button> : null}</div></form><section className="overflow-hidden rounded-2xl border border-brand-border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-brand-muted text-xs uppercase text-brand-softText"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Slug</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-brand-border">{items.map((item) => <tr key={item.id}><td className="px-4 py-4 font-bold">{item.name}</td><td className="px-4 py-4 text-brand-softText">{item.slug}</td><td className="px-4 py-4"><button onClick={() => { setEditing(item); setName(item.name); setSlug(item.slug); }} className="mr-2 rounded-lg border border-brand-border px-3 py-1.5 font-bold">Edit</button><button onClick={() => { if (window.confirm('Delete this tag?')) void deleteTag(item.id).then(load).catch((err) => setError(err.message)); }} className="rounded-lg border border-red-200 px-3 py-1.5 font-bold text-red-700">Delete</button></td></tr>)}</tbody></table></section></div></div>;
}
